# Generated by Django 4.1 on 2022-08-11 21:51

import functools

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.wallets.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            apps.wallets.utils.generate_code, *(), **{"length": 16, "prefix": "WLT"}
                        ),
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="years", to="wallets.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("value", models.FloatField()),
                ("payer_or_receiver", models.CharField(max_length=400)),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                ("group_code", models.CharField(editable=False, max_length=16)),
                ("installment", models.PositiveIntegerField(default=1)),
                ("quantity_of_installments", models.PositiveIntegerField(default=1)),
                (
                    "record_type",
                    models.CharField(
                        choices=[("debit", "debit"), ("credit", "credit"), ("deposit", "deposit")],
                        max_length=64,
                    ),
                ),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="month",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="months", to="wallets.year"
            ),
        ),
        migrations.CreateModel(
            name="DepositRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("receipt_date", models.DateField()),
                ("payer", models.CharField(max_length=400)),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("value", models.FloatField()),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                ("group_code", models.CharField(editable=False, max_length=16)),
                ("recurrences", models.PositiveIntegerField(default=1)),
                ("recurrence_number", models.PositiveIntegerField(default=1)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("receiver", models.CharField(max_length=400)),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("price", models.FloatField()),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                ("group_code", models.CharField(editable=False, max_length=16)),
                ("recurrences", models.PositiveIntegerField(default=1)),
                ("recurrence_number", models.PositiveIntegerField(default=1)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("receiver", models.CharField(max_length=400)),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("number_of_installments", models.PositiveIntegerField(default=1)),
                ("installment", models.PositiveIntegerField(default=1)),
                ("total_price", models.FloatField()),
                ("installment_value", models.FloatField(default=0)),
                ("code", models.CharField(editable=False, max_length=16, unique=True)),
                ("group_code", models.CharField(editable=False, max_length=16)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
    ]
