# Generated by Django 4.1 on 2022-08-11 02:32

import apps.wallets.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            apps.wallets.utils.generate_code, *(), **{"length": 16, "prefix": "WLT"}
                        ),
                        editable=False,
                        max_length=16,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Year",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="years", to="wallets.wallet"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Month",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="months", to="wallets.year"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebitRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("receiver", models.CharField(max_length=400)),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("price", models.FloatField()),
                ("recurrences", models.IntegerField(default=1)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debit_records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("receiver", models.CharField(max_length=400)),
                ("comments", models.CharField(blank=True, max_length=500)),
                ("number_of_installments", models.IntegerField(default=1)),
                ("installment", models.IntegerField(default=1)),
                ("total_price", models.FloatField()),
                ("installment_value", models.FloatField(default=0)),
                (
                    "month",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_records",
                        to="wallets.month",
                    ),
                ),
            ],
        ),
    ]
